/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DirectionMenu: typeof import('./src/components/SubTab/DirectionMenu.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Main: typeof import('./src/components/Layout/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    StandardItem: typeof import('./src/components/SubTab/SubTabItem/StandardItem.vue')['default']
    SubTab: typeof import('./src/components/SubTab/SubTab.vue')['default']
    Test: typeof import('./src/components/SubTab/SubTabItem/test.vue')['default']
  }
}
